# ==============================================================================
# scMax 基础环境配置文件 (Base Config)
# 此文件用于存放所有实验项目共用的基础环境变量、物种说明和公共挂载目录。
# 个人分析的特定参数（如 resolurions, do_cluster 等）请在执行 scMax.py 时通过 CLI 参数传入。
# ==============================================================================

global_outdir: "./scMax_Out"
Rscript_path: "Rscript"

# ------ 全局核心元数据配置 ------
Database_Info:
  run: false                 # 是否连通知识图谱与后台数据库登记
  
  # ------ 知识图谱与后台数据库登记信息（保持与 config_template 词条全小写规范一致） ------
  std_project_id: ""              # 标分项目编号
  custom_project_id: "scMax_Demo" # 个性化项目编号 (原 Project_Name)
  crm_id: ""                      # crm下单编号
#  annotation_level: "MajorType"   # 分群层次 (重要，直接影响分析层级界定)
  species: "Human"                # 物种信息 (英文，原 Species / species)
  species_zh: "人"                 # 物种中文信息
  tissue_type: "PBMC"             # 组织类型英文 (原 Organ)
  tissue_type_zh: "外周血单核"     # 组织类型中文
  disease_type: "Healthy"         # 疾病类型 (原 Disease)
  seq_tech: "10x scRNA-seq"       # 测序技术平台
  analyst: ""                     # 分析人
  notes: ""                       # 备注
