[data]
f01_rdsfile=/annoroad/data1/bioinfo/PROJECT/RD/Cooperation/smarttools/PMO/yaojiaying/Hiplot/integrate_cluster/content/integrate_cluster/test/input/Filtered1.rds
f02_metadatafile=/annoroad/data1/bioinfo/PROJECT/RD/Cooperation/smarttools/PMO/yaojiaying/Hiplot/integrate_cluster/content/integrate_cluster/test/input/Filtered1_metadata.csv

[integrate_ana]
debatch_method=harmony
#debatch_method=harmony,cca,pca,none
debatch_object=Sample
nvariablefeatures = 2000
reduction_npc_num = 20

[cluster_ana]
resolution = 0.4
#resolution = 0.4,0.6,0.8
