########################### 通用参数 ##############################
[Para]
# outdir：必选参数
outdir=/annogene/data2/bioinfo/SCV/Repositories/Module/ManualAnnoReport/ManualAnnoReport_v1.0/test
# inputrds：必选参数，单选
inputrds=/annogene/data2/bioinfo/SCV/PROJECT/Customized_project/Personalized_packages/C019/5_HumanscRNA_6sample/1_QC.MajorType/1_MajorType/Rdata/Data-Clustered.rds
# metacsv：可选参数，用于更新rds中的metadata信息
metacsv=
# sample_col：必选参数，单选，样本列名，在报告中样本统计部分进行展示
sample_col=orig.ident
# sample_order：可选参数，如果有则按照这个顺序进行绘图
sample_order=
# group_col：可选参数，分组列名，可单选可多选或不选，一定不能叫Sample。每个组都会绘图，在分析报告分组统计部分对第一个组进行展示
group_col=Group,Age
# group_order：可选参数，仅对group_col中第一个组添加分组展示顺序
group_order=Child,Adolescent,Adult,MidAge,Aged
# organism_kegg：必选参数，物种GO数据库
orgdb=org.Hs.eg.db
# organism_kegg:必选参数，物种KEGG数据库
organism_kegg=hsa

########################### Part1 参数：用于cluster绘图，参考marker绘图 ###########################
# refmarker.file：可选参数，单选，如果有则绘制参考marker表达图，文件用tab键分割，列名为CellType, Markers，其中Markers列的基因用英文逗号分隔。推荐方法：在excel中填写信息后复制到服务器写入新文件
refmarker.file=/annogene/data2/bioinfo/SCV/PROJECT/Customized_project/Personalized_packages/C019/5_HumanscRNA_6sample/1_QC.MajorType/1_MajorType/refmarkers.xls
# cluster_col：可选参数，细胞cluster列名，单选，如果不提供，则使用seurat_clusters列
cluster_col=seurat_clusters
# cluster_col：可选参数，多选，细胞cluster分群颜色，如果不提供或者个数小于分群个数，则使用默认颜色Paired色板。颜色填写需要前后加引号，示例"#00D5FF,#3f51b5,#C0A9FF,#FF69B4"
cluster_colors=

########################### Part2 参数：用于细胞类型注释绘图，生成报告 ###########################
# annofile：必选参数，单选，细胞类型注释文件，文件用tab键分割，由三列组成，列名为Cluster,CellType,Markers，其中Markers列的基因用英文逗号分隔。推荐方法：在excel中填写信息后复制到服务器写入新文件
annofile=/annogene/data2/bioinfo/SCV/PROJECT/Customized_project/Personalized_packages/C019/5_HumanscRNA_6sample/1_QC.MajorType/1_MajorType/celltype.anno.csv
# celltype.levels：可选参数，细胞类型顺序，如果不提供，则自动排序
celltype.levels=SSC,SPG,SPC.L,SPC.Z,SPC.P,SPC.D,SPT,SC,LC,Myeloid,T cells,Mix
# celltype.keep：必选参数，细胞类型保留列表，必须包含在celltype.levels中
celltype.keep=SSC,SPG,SPC.L,SPC.Z,SPC.P,SPC.D,SPT,SC,LC,Myeloid,T cells
# celltype_col：可选参数，单选，细胞类型列名，如果不提供，则使用CellType
celltype_col=CellType
# celltype_colors：可选参数，多选，细胞类型颜色，如果不提供或者个数小于细胞类型个数，则使用默认颜色Paired色板。示例#00D5FF,#3f51b5,#C0A9FF,#FF69B4
celltype_colors=
# rdsprefix：可选参数，rds文件前缀，如果不提供，则使用Annotation
rdsprefix=MajorType

